
- name: instalando apache2 no debian
  package: 
   name: apache2 
   state: present
  when: ansible_os_family == "Debian"


- name: instalando apache2 no centos
  package: 
   name: httpd
   state: present
  when: ansible_os_family == "RedHat"
